### ISSUE TITLE
README

### ISSUE THREAD

**Issue by noraj** [Tethik/drupal-module-enumeration#3]
could you provide a more extensive README to help understand what drupal-module-enumeration really does? Just a wordlist attack ? Version supported ? etc.

**Comment by Tethik** [comment]
Welcome to a five year old experiment/attack I spent about one hour on and then haven't touched since lol. Sorry to disappoint, I'm not even sure it works correctly :)

Yes, just a wordlist attack based on at the time the most popular modules.
Version supported: no idea.

**Comment by Tethik** [comment]
I think you accomplish the same as this tool using `nmap` with the `http-drupal-enum` plugin. Pretty sure that's also where I got the wordlist from. I'm going to archive this project now and leave a note in the readme. Thanks for your interest though!
